package pelep.unlittorch;

import static pelep.unlittorch.UnlitTorchPlugin.MOD_NAME;
import static pelep.unlittorch.UnlitTorchPlugin.MOD_ID;
import static pelep.unlittorch.UnlitTorchPlugin.MOD_VERSION;
import static pelep.unlittorch.UnlitTorchPlugin.MOD_MCVERSION;
import static pelep.unlittorch.UnlitTorchPlugin.MOD_DEPENDENCIES;

import java.io.File;
import java.util.Arrays;

import pelep.unlittorch.config.ConfigCommon;
import pelep.unlittorch.proxy.ProxyCommon;
import pelep.unlittorch.handler.ConnectionHandler;
import pelep.unlittorch.handler.LogHandler;
import pelep.unlittorch.handler.PacketReceiver;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkMod.SidedPacketHandler;

@Mod(name = MOD_NAME, modid = MOD_ID, version = MOD_VERSION, acceptedMinecraftVersions = MOD_MCVERSION, dependencies = MOD_DEPENDENCIES)
@NetworkMod(clientSideRequired = true, serverSideRequired = true, clientPacketHandlerSpec = @SidedPacketHandler(channels = MOD_ID, packetHandler = PacketReceiver.class), connectionHandler = ConnectionHandler.class)
public class UnlitTorch
{
    @Instance(MOD_ID)
    public static UnlitTorch instance;
    
    @SidedProxy(clientSide = "pelep.unlittorch.proxy.ProxyClient", serverSide = "pelep.unlittorch.proxy.ProxyCommon")
    public static ProxyCommon proxy;
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent e)
    {
        LogHandler.init();
        ModMetadata md = e.getModMetadata();
        
        md.autogenerated = false;
        md.description = "Unlit torches! Lanterns! This mod adds unlit torches and lanterns to the game and also modifies other vanilla behavior.";
        md.credits = "Many thanks to Mojang, MCP, and FML";
        md.authorList = Arrays.asList(new String[] {"pelep"});
        md.url = "http://www.minecraftforum.net/topic/1690690-";
        
        proxy.setUpConfig(new File(e.getModConfigurationDirectory(), MOD_ID + MOD_VERSION + ".cfg"));
    }
    
    @EventHandler
    public void init(FMLInitializationEvent e)
    {
        proxy.registerTorches();
        proxy.registerBlocks();
        proxy.registerItems();
        proxy.registerRenderers();
        proxy.registerVillager();
        proxy.registerLoot();
        proxy.registerTileEntities();
        proxy.registerTrackers();
    }
    
    @EventHandler
    public void postInit(FMLPostInitializationEvent e)
    {
        ConfigCommon.postInit();
        proxy.registerRecipes();
        proxy.checkTorches();
    }
}
